### ISSUE TITLE
Process fails when trying to decrypt repository

### ISSUE THREAD

**Issue by crscheid** [crscheid/image-watcher#10]
Need to robustify this a little more:

```
[2016-10-28 19:39:25] image-watcher.ERROR: Could not remove old files from Seafile. Error message: cURL error 7: Failed to connect to server.xxx port 12347: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) [] []
[2016-10-28 19:39:25] image-watcher.INFO: Requesting library decryption [] []
[2016-10-28 19:39:25] image-watcher.INFO: Decrypting library resource: 4bd34bc0-a274-4f89-bf7a-23adfb5f8154 [] []

Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to server.xxx port 12347: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Obje in /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
```

**Comment by crscheid** [comment]
Closing issue as this is a duplicate.
