### ISSUE TITLE
PHP process crashes after a period of time

### ISSUE THREAD

**Issue by crscheid** [crscheid/image-watcher#7]

**Comment by crscheid** [comment]
Looks like there might be an issue with throttling requests on the Seafile end:

`
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error:`DELETE https://xxxx:12347/api2/repos/4bd34bc0-a274-4f89-bf7a-23adfb5f8154/file/?p=/Images/2016-09-16-06-14-31.jpg`resulted in a`429 UNKNOWN STATUS CODE`response:
{"detail": "Request was throttled.Expected available in 1 second."}
 in /usr/src/app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /usr/src/app/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /usr/src/app/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /usr/src/app/vendor/guzzle in /usr/src/app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107
`
